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

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,24 +23,14 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        
-    - name: Run tests
-      id: tests
-      run: python src/test.py
-      
-    - name: Check test results
-      if: steps.tests.outcome == 'failure'
-      run: |
-        echo "Tests failed. Exiting workflow."
-        exit 1
+        pip install -r requirements.txt        
 
     - name: List directory contents
       run: ls -al
 
     - name: Run build.py
       run: python build.py
-      
+
     - name: List directory contents
       run: ls -al
     
@@ -51,4 +41,14 @@ jobs:
           echo "Expected 2 new files but found $NEW_FILES_COUNT"
           exit 1
         fi
+
+    - name: Run tests
+      id: tests
+      run: python src/test.py
+      
+    - name: Check test results
+      if: steps.tests.outcome == 'failure'
+      run: |
+        echo "Tests failed. Exiting workflow."
+        exit 1
 
